linters:
  InlineStyles:
    exclude:
      - 'templates/activity/_activity.haml'
  LineLength:
    max: 150
  SpaceInsideHashAttributes:
    style: no_space
  ViewLength:
    exclude:
      - 'templates/activity/_activity.haml'
