inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'spec/integration/test_repo/**/*'
    - 'spec/integration/test_repo_tree/**/*'
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 140
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

RSpec/ExampleLength:
  Max: 21
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
