inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/integration/test_repo/**/*'
    - 'spec/integration/test_repo_tree/**/*'
  NewCops: enable
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
